apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: calibrate-ptycho
  labels:
    workflows.diamond.ac.uk/science-group-imaging: "true"
  annotations:
    workflows.argoproj.io/title: Calibrate ptycho STEM data
    workflows.argoproj.io/description: |
      A utility which takes in a 4D STEM data set and outs the approximate real space pixel size, measured camera length and scan rotation, based off dpc
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/imaging-workflows"
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schema/notebook_Schema.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schema/notebook_ui.json" | nindent 6 }}
spec:
  entrypoint: calibration-notebook
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
  volumeClaimTemplates:
  - metadata:
      name: tmp
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: netapp

  templates:
    - name: calibration-notebook
      steps:
      - - name: copy-notebook
          template: mount-files
      - - name: run-notebook
          template: notebook

    - name: mount-files
      script:
        image: debian:stable-slim
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: session
          mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
        command: [bash]
        source: |
          OUTPUT="{{`{{workflow.parameters.visitdir}}`}}"/processing/workflows/
          mkdir -p $OUTPUT
          echo "something!"
          echo '{{ .Files.Get "notebooks/Ptycho_calibration.ipynb" | b64enc }}' | base64 -d > $OUTPUT/Ptycho_calibration.ipynb
    
    - name: notebook
      inputs:
        parameters:
        - name: sample
          value: "{{`{{workflow.parameters.sample}}`}}"
        - name: timestamp
          value: "{{`{{workflow.parameters.timestamp}}`}}"
        - name: outpath
          value: "{{`{{workflow.parameters.outpath}}`}}"
        - name: thresh_lower
          value: "{{`{{workflow.parameters.thresh_lower}}`}}"
        - name: thresh_upper
          value: "{{`{{workflow.parameters.thresh_upper}}`}}"
      script:
        image: gitlab.diamond.ac.uk:5050/scisoft/ptychography/dimtools/mib2x
        volumeMounts:
        - name: session
          mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
        - name: tmp
          mountPath: /tmp
        - name: software
          mountPath: /dls_sw/e02/medipix_mask
        command: [bash]
        source: |
          ERROR_TXT="raise error"
          ERROR_STR="An error occured within the notebook. Please open the output file to check"
          OUTPUT="{{`{{workflow.parameters.visitdir}}`}}"/processing/workflows/
          python -m papermill "{{`{{workflow.parameters.visitdir}}`}}"/processing/workflows/Ptycho_calibration.ipynb $OUTPUT/Calibrate-notebook.ipynb \
            -p visit "{{`{{ workflow.parameters.visitdir }}`}}"
            -p sample "{{`{{ workflow.parameters.sample }}`}}"
            -p timestamp "{{`{{workflow.parameters.timestamp}}`}}"
            -p maskpath /software/29042024_12bitmask2.h5
            -p outpath "{{`{{workflow.parameters.outpath}}`}}"
            -p lower "{{`{{workflow.parameters.thresh_lower}}`}}"
            -p upper "{{`{{workflow.parameters.thresh_upper}}`}}"
            > $OUTPUT/papermill.log 2>&1

          python  -m jupyter nbconvert $OUTPUT/Calibrate-notebook.ipynb \
            --to html 

      outputs:
        artifacts:
        - name: phase-output
          path: "{{`{{ inputs.parameters.outpath }}`}}/phase-output.html"
          archive:
            none: {}
        - name: notebook-log
          path: "{{`{{ inputs.parameters.outpath }}`}}/papermill.log"
          archive:
            none: {}
      podSpecPatch: |
        containers:
        - name: main
          resources:
            requests:
              cpu: 10
              memory: 50Gi
            limits:
              cpu: 10
              memory: 50Gi

        