apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ptypy-example
spec:
  entrypoint: ptypy-test-with-cli
  volumeClaimTemplates:
  - metadata:
      name: tmpdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
  templates:
  - name: ptypy-test-with-cli
    inputs:
      parameters:
      - name: config
      - name: id
      - name: output
    container:
      image: gcr.io/diamond-privreg/ptypy/test_with_cli:0.1
      env:
        - name: CUPY_CACHE_DIR
          value: /tmp/.cupy/kernel_cache
      command:
      - ptypy.cli
      args: ["-j", "{{ inputs.parameters.config }}", "-i", "{{ inputs.parameters.id }}", "-o", "{{ inputs.parameters.output }}", "-s", "hdf5_loader", "-b", "cupy"]
      volumeMounts:
        - name: session
          mountPath: "{{ workflow.parameters.visitdir }}"
        - name: tmpdir
          mountPath: /tmp
      resources:
        requests:
          cpu: 1
          memory: 20Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: 1
          memory: 50Gi
          nvidia.com/gpu: "1"
    tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: gpu
      effect: NoSchedule
    volumes:
    - name: session
      hostPath:
        path:  "{{ workflow.parameters.visitdir }}"
        type: Directory
