apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dpc
  annotations:
    workflows.argoproj.io/title: dpc
    workflows.argoproj.io/description: |
      dpc is an utility to take a scan file inpath, reconstruct the differential phase contrast (DPC) images, and save the results to an outpath.
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schema/dpcSchema.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schema/dpcUISchema.json" | nindent 6 }}
spec:
  entrypoint: dpc
  arguments:
    parameters:
      - name: visitdir
        valueFrom:
          configMapKeyRef:
            name: sessionspaces
            key: data_directory
  templates:
    - name: dpc
      inputs:
        parameters:
          - name: visitDir
            value: ""
          - name: outputFolder
            value: ""
          - name: singleFirst
            value: 0
      volumes:
        - name: session
          hostPath:
            path: "{{`{{workflow.parameters.visitdir}}`}}`}}"
            type: Directory
