apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ptypy-i08-1-from-config
  labels:
    workflows.diamond.ac.uk/science-group-imaging: "true"
  annotations:
    workflows.argoproj.io/title: PtyPy Reconstruction for I08-1
    workflows.argoproj.io/description: |
      Runs a PtyPy reconstruction job inside a container based on data collected at I08-1.
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/imaging-workflows"
    workflows.diamond.ac.uk/parameter-schema.id: |
      {
        "title": "Scan Number",
        "type": "integer"
      }
    workflows.diamond.ac.uk/parameter-schema.outpath: |
      {
        "title": "Path to output folder",
        "type": "string",
        "default": "processing/workflows/ptypy"
      }
    workflows.diamond.ac.uk/parameter-schema.nprocs: |
      {
        "title": "Nr. of processes",
        "type": "integer",
        "default": 1
      }
    workflows.diamond.ac.uk/parameter-schema.memory: |
      {
        "title": "Requested CPU memory",
        "type": "string",
        "pattern": "^[0-9]+[GMK]i$",
        "default": "100Gi"
      }
    workflows.diamond.ac.uk/parameter-schema.usegpu: |
      {
        "title": "Use GPU",
        "type": "boolean",
        "default": true
      }
    workflows.diamond.ac.uk/parameter-schema.numiter: |
      {
        "title": "Nr. of iterations",
        "type": "integer",
        "default": 100
      }
    workflows.diamond.ac.uk/parameter-schema.probemodes: |
      {
        "title": "Nr. of probe modes",
        "type": "integer",
        "default": 1
      }
      
spec:
  entrypoint: ptypy-pipeline
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
    - name: id
      value: "77113"
    - name: outpath
      value: "processing/workflows/ptypy"
    - name: nprocs
      value: "1"
    - name: memory
      value: 100Gi
    - name: usegpu
      value: "true"
    - name: numiter
      value: "100"
    - name: probemodes
      value: "1"
  volumeClaimTemplates:
  - metadata:
      name: tmpdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: netapp
      
  templates:
  - name: ptypy-setup
    script:
      image: python:3.14
      volumeMounts:
      - name: session
        mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      - name: tmpdir
        mountPath: /tmp
      command: [bash]
      source: | 
          OUTPUT="{{`{{ workflow.parameters.visitdir }}`}}"/"{{`{{ workflow.parameters.outpath }}`}}"
          mkdir -p $OUTPUT
          INPUT="{{`{{ workflow.parameters.visitdir }}`}}"/nexus
          ID="{{`{{ workflow.parameters.id }}`}}"
          mkdir -p $OUTPUT/scan_$ID
          NUMITER="{{`{{ workflow.parameters.numiter }}`}}"
          PROBEMODES="{{`{{ workflow.parameters.probemodes }}`}}"
          echo '{{ .Files.Get "config/i08-1_raar.yaml" | b64enc }}' | base64 -d > $OUTPUT/scan_$ID/ptypy_config.yaml
          sed -i "s;<INPATH>;$INPUT/;" $OUTPUT/scan_$ID/ptypy_config.yaml
          sed -i "s;<NUMITER>;$NUMITER;" $OUTPUT/scan_$ID/ptypy_config.yaml
          sed -i "s;<PROBEMODES>;$PROBEMODES;" $OUTPUT/scan_$ID/ptypy_config.yaml
          "{{`{{ workflow.parameters.usegpu }}`}}" && sed -i "s;RAAR;RAAR_cupy;" $OUTPUT/scan_$ID/ptypy_config.yaml
          cat $OUTPUT/scan_$ID/ptypy_config.yaml
    outputs:
      parameters:
        - name: config
          value: "{{`{{ workflow.parameters.visitdir }}`}}/{{`{{ workflow.parameters.outpath }}`}}/scan_{{`{{ workflow.parameters.id }}`}}/ptypy_config.yaml"
    volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory

  - name: get-filepath
    inputs:
      parameters:
      - name: config
    script:
      image: python:3.14
      volumeMounts:
      - name: session
        mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      - name: tmpdir
        mountPath: /tmp
      command: [python]
      source: |
        import re
        OUTPATH="{{`{{ workflow.parameters.visitdir }}`}}/{{`{{ workflow.parameters.outpath }}`}}"
        SCAN="{{`{{ workflow.parameters.id }}`}}"
        CONFIG="{{`{{ inputs.parameters.config }}`}}"
        with open("/tmp/out.txt", "w") as o:
          with open(CONFIG, 'r') as f:
            text = f.read()
            ENGINE = re.findall("    engine0:\n      name: (.*)", text)[0]
            NITER = int(re.findall("      numiter: (.*)", text)[0])
            o.write(f"{OUTPATH}/scan_{SCAN}/{SCAN}_{ENGINE}_{NITER:04d}.ptyr")
    outputs:
      parameters:
      - name: filepath
        valueFrom:
          path: /tmp/out.txt
    volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  - name: ptypy-pipeline
    dag:
      tasks:
      - name: prepare
        template: ptypy-setup
      - name: reconstruct-with-gpu
        when: "{{`{{ workflow.parameters.usegpu }}`}} == true" 
        templateRef:
          name: ptypy-generic
          template: ptypy-gpu-run
          clusterScope: true
        depends: "prepare"
        arguments:
          parameters:
          - name: config
            value: "{{`{{ tasks.prepare.outputs.parameters.config }}`}}"
          - name: id
            value: "{{`{{ workflow.parameters.id }}`}}"
          - name: outpath
            value: "{{`{{ workflow.parameters.visitdir }}`}}/{{`{{ workflow.parameters.outpath }}`}}"
          - name: nprocs
            value: "{{`{{ workflow.parameters.nprocs }}`}}"
          - name: memory
            value: "{{`{{ workflow.parameters.memory }}`}}"
      - name: reconstruct-with-cpu
        when: "{{`{{ workflow.parameters.usegpu }}`}} == false"
        templateRef:
          name: ptypy-generic
          template: ptypy-cpu-run
          clusterScope: true
        depends: "prepare"
        arguments:
          parameters:
          - name: config
            value: "{{`{{ tasks.prepare.outputs.parameters.config }}`}}"
          - name: id
            value: "{{`{{ workflow.parameters.id }}`}}"
          - name: outpath
            value: "{{`{{ workflow.parameters.visitdir }}`}}/{{`{{ workflow.parameters.outpath }}`}}"
          - name: nprocs
            value: "{{`{{ workflow.parameters.nprocs }}`}}"
          - name: memory
            value: "{{`{{ workflow.parameters.memory }}`}}"
      - name: get-filepath
        template: get-filepath
        depends: "reconstruct-with-gpu || reconstruct-with-cpu"
        arguments:
          parameters:
          - name: config
            value: "{{`{{ tasks.prepare.outputs.parameters.config }}`}}"
      - name: plot
        templateRef:
          name: ptypy-utils
          template: ptypy-plotting
          clusterScope: true
        depends: "get-filepath"
        arguments:
          parameters:
          - name: filepath
            value: "{{`{{tasks.get-filepath.outputs.parameters.filepath}}`}}"
