apiVersion: v2
name: xrd1d
description: XRD1D is a utility which performs Azimuthal integration (ExcaliburXRDIntegration), removes/smooths background if needed, writes the spectrum to the output file.
type: application
version: 0.0.1
