apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: e02-mib2x
  annotations:
  workflows.argoproj.io/title: ePSIC mib conversion
  workflows.argoproj.io/description: |
    Convert MIB file to hdf5/hspy files
  workflows.diamond.ac.uk/parameter-schema.mib_path: |
    {
      "type": "string"
    }
  workflows.diamond.ac.uk/parameter-schema.reshape_option: |
    {
      "type": "string",
      "enum": [
        "--auto-reshape",
        "--no-reshaping",
        "--use-fly-back",
        "--known-shape"
      ],
      "default": "--auto-reshape"
    }
  workflows.diamond.ac.uk/parameter-schema.Scan_X: |
    {
      "type": "integer",
      "default": 256
    }
  workflows.diamond.ac.uk/parameter-schema.Scan_Y: |
    {
      "type": "integer",
      "default": 256
    }
  workflows.diamond.ac.uk/parameter-schema.iBF: |
    {
      "type": "boolean",
      "default": true
    }
  workflows.diamond.ac.uk/parameter-schema.bin_sig_factor: |
    {
      "type": "integer",
      "minimum": 0,
      "maximum": 8,
      "default": 4
    }
  workflows.diamond.ac.uk/parameter-schema.bin_nav_factor: |
    {
      "type": "integer",
      "minimum": 0,
      "maximum": 8,
      "default": 4
    }
  workflows.diamond.ac.uk/parameter-schema.create_json: |
    {
      "type": "boolean",
      "default": true
    }
  workflows.diamond.ac.uk/parameter-schema.ptycho_config: |
    {
      "type": "string",
      "default": ""
    }
  workflows.diamond.ac.uk/parameter-schema.ptycho_template: |
    {
      "type": "string",
      "default": ""
    }
  workflows.diamond.ac.uk/parameter-schema.nprocs: |
    {
      "type": "integer",
      "default": 8
    }
  workflows.diamond.ac.uk/parameter-schema.memory: |
    {
      "type": "string",
      "pattern": "^[0-9]+[GMK]i$",
      "default": "16Gi"
    }
  workflows.diamond.ac.uk/parameter-schema.DEBUG: |
    {
      "type": "integer",
      "default": 1
    }
spec:
  entrypoint: mib2x
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
  templates:
  - name: mib2x
    inputs:
      parameters:
      - name: mib_path
      - name: reshape_option
        value: "--auto-reshape"
      - name: Scan_X
        value: 256
      - name: Scan_Y
        value: 256
      - name: iBF
        value: true
      - name: bin_sig_factor
        value: 4
      - name: bin_nav_factor
        value: 4
      - name: create_json
        value: true
      - name: ptycho_config
        value: ""
      - name: ptycho_template
        value: ""
      - name: nprocs
        value: 8
      - name: memory
        value: 16Gi
      - name: DEBUG
        value: 1
    container:
      image: ghcr.io/epsic-dls/mib2x:1.0.0
      imagePullPolicy: Always
      env:
      - name: BLOSC_NTHREADS
        value: "{{ inputs.parameters.nprocs }}"
      - name: OMP_NUM_THREADS
        value: "{{ inputs.parameters.nprocs }}"
      - name: M2X_DEBUG
        value: "{{ inputs.parameters.DEBUG }}"
      command: [python]
      args:
      - "mib_convert.py"
      - "{{ inputs.parameters.mib_path }}"
      - "{{ inputs.parameters.reshape_option }}"
      - "--scan-x={{ inputs.parameters.Scan_X }}"
      - "--scan-y={{ inputs.parameters.Scan_Y }}"
      - "{{ inputs.parameters.iBF }}"
      - "--bin-sig-factor={{ inputs.parameters.bin_sig_factor }}"
      - "--bin-nav-factor={{ inputs.parameters.bin_nav_factor }}"
      - "{{ inputs.paramters.create_json }}"
      - "--ptycho-config={{ inputs.paramters.ptycho_config }}"
      - "--ptycho-template={{ inputs.paramters.ptycho_template }}"
      volumeMounts:
      - name: session
        mountPath: "{{ workflow.parameters.visitdir }}"
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            cpu: "{{ inputs.parameters.nprocs }}"
            memory: "{{ inputs.parameters.memory }}"
          limits:
            cpu: "{{ inputs.parameters.nprocs }}"
            memory: "{{ inputs.parameters.memory }}"
    volumes:
    - name: session
      hostPath:
        path:  "{{ workflow.parameters.visitdir }}"
        type: Directory
    tolerations:
    - key: nodetype
      operator: Equal
      value: cs05r_gpfs
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: has_gpfs03
              operator: In
              values:
              - "true"
