apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: xrd1d-batch
  annotations:
    workflows.argoproj.io/title: XRD (X-ray Diffraction) - 1D maps
    workflows.argoproj.io/description: |
      XRD can be used to spatially map changes in crystallographic direction, d-spacing or strain across a sample. A 2D XRD pattern is collected per pixel, in concert with the XRF signal.
      Using this notebook, an Azimuthal integration is performed to present the XRD data as one-line graphical representation, removing/smoothing the background if needed.
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schema/batchSchema.json" | nindent 6 }}
      {{- .Files.Get "schema/xrd1dSchema.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schema/batchUISchema.json" | nindent 6 }}
      {{- .Files.Get "schema/xrd1dUISchema.json" | nindent 6 }}
spec:
  entrypoint: xrd1d-batch
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
    - name: outputFolder
      value: /tmp/output
    - name: scanNumbers
      value: "[391572]"
    - name: xrdProcessConfigUpload
      value: ""
    - name: calibrationPath
      value: ""
    - name: maskPath
      value: ""
    - name: flatPath
      value: ""
    - name: backgroundType
      value: ""
    - name: polynomialOrder
      value: 0
  volumeClaimTemplates:
  - metadata:
      name: tmp
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: netapp
  templates:
  - name: xrd1d-mount-files
    script:
      image: gitlab.diamond.ac.uk:5050/i14/i14_utility/xrd:v0.1
      command: [bash]
      source: |
        echo '{{ .Files.Get "notebooks/xrd1d_batch3.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
      volumeMounts:
      - name: tmp
        mountPath: /tmp
  - name: xrd1d-notebook
    steps:
    - - name: loop-notebooks
        template: gen-notebook
        arguments:
          parameters:
          - name: outputFolder
            value: "{{`{{ workflow.parameters.outputFolder }}`}}"
          - name: scanNumber
            value: "{{`{{ item }}`}}"
          - name: xrdProcessConfigUpload
            value: "{{`{{ workflow.parameters.xrdProcessConfigUpload }}`}}"
          - name: calibrationPath
            value: "{{`{{ workflow.parameters.calibrationPath }}`}}"
          - name: maskPath
            value: "{{`{{ workflow.parameters.maskPath }}`}}"
          - name: flatPath
            value: "{{`{{ workflow.parameters.flatPath }}`}}"
          - name: backgroundType
            value: "{{`{{ workflow.parameters.backgroundType }}`}}"
          - name: polynomialOrder
            value: "{{`{{ workflow.parameters.polynomialOrder }}`}}"
        withParam: "{{`{{ workflow.parameters.scanNumbers }}`}}"
  - name: gen-notebook
    inputs:
      parameters:
      - name: outputFolder
      - name: scanNumber
      - name: xrdProcessConfigUpload
      - name: calibrationPath
      - name: maskPath
      - name: flatPath
      - name: backgroundType
      - name: polynomialOrder
    script:
      image: gitlab.diamond.ac.uk:5050/i14/i14_utility/xrd:v0.1
      env:
      - name: HOME
        value: /tmp
      command: [bash]
      source: |
        python -m papermill /tmp/notebook.ipynb /tmp/notebook-parametrized.ipynb \
          -p inpath "{{`{{ workflow.parameters.visitdir }}`}}/scan/i14-{{`{{ inputs.parameters.scanNumber }}`}}.nxs" \
          -p process_configfile "{{`{{ inputs.parameters.xrdProcessConfigUpload }}`}}" \
          -p outpath "{{`{{ inputs.parameters.outputFolder }}`}}/i14-{{`{{ inputs.parameters.scanNumber }}`}}-xrd1d.nxs" \
          -p calibration_path "{{`{{ inputs.parameters.calibrationPath }}`}}" \
          -p mask_path "{{`{{ inputs.parameters.maskPath }}`}}" \
          -p flat_path "{{`{{ inputs.parameters.flatPath }}`}}" \
          -p background_type "{{`{{ inputs.parameters.backgroundType }}`}}" \
          -p polynomial_order "{{`{{ inputs.parameters.polynomialOrder }}`}}"
        python -m jupyter nbconvert /tmp/notebook-parametrized.ipynb --to notebook --execute --allow-errors --output xrd1d-notebook-{{`{{ inputs.parameters.scanNumber }}`}} --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
        python -m jupyter nbconvert "{{`{{ inputs.parameters.outputFolder }}`}}/xrd1d-notebook-{{`{{ inputs.parameters.scanNumber }}`}}.ipynb" --to html --no-input --output xrd1d-output-{{`{{ inputs.parameters.scanNumber }}`}} --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
      volumeMounts:
      - name: session
        mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      - name: tmp
        mountPath: /tmp
    outputs:
      artifacts:
      - name: xrd1d-output
        path: "{{`{{ inputs.parameters.outputFolder }}`}}/xrd1d-output-{{`{{ inputs.parameters.scanNumber }}`}}.html"
        archive:
          none: {}
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            cpu: 10
            memory: 30Gi
          limits:
            cpu: 10
            memory: 30Gi
    tolerations:
    - key: nodegroup
      operator: Equal
      value: workflows
      effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: nodegroup
              operator: In
              values:
              - workflows
    volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  - name: xrd1d-batch
    dag:
      tasks:
      - name: files
        template: xrd1d-mount-files
      - name: notebook
        template: xrd1d-notebook
        dependencies: [files]
