apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: xrd2d
  annotations:
    workflows.argoproj.io/title: xrd2d
    workflows.argoproj.io/description: |
      xrd2d is a utility which performs Azimuthal integration (ExcaliburXRDIntegration) and saves result to a nxs file
    workflows.diamond.ac.uk/parameter-schema: |
      {{- .Files.Get "schema/xrd2dSchema.json" | nindent 6 }}
    workflows.diamond.ac.uk/ui-schema: |
      {{- .Files.Get "schema/xrd2dUISchema.json" | nindent 6 }}
spec:
  entrypoint: xrd2d
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
    - name: outputFolder
      value: /tmp/output
    - name: singleFirst
      value: 391572
    - name: xrdProcessConfigUpload
      value: ""
    - name: calibrationPath
      value: ""
    - name: maskPath
      value: ""
    - name: flatPath
      value: ""
  volumeClaimTemplates:
  - metadata:
      name: tmp
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: netapp
  templates:
  - name: xrd2d-mount-files
    script:
      image: gitlab.diamond.ac.uk:5050/i14/i14_utility/xrd:v0.1
      command: [bash]
      source: |
        echo '{{ .Files.Get "notebooks/xrd2d_batch3.ipynb" | b64enc }}' | base64 -d > /tmp/notebook.ipynb
      volumeMounts:
      - name: tmp
        mountPath: /tmp
  - name: xrd2d-notebook
    inputs:
      parameters:
      - name: outputFolder
        value: "{{`{{ workflow.parameters.outputFolder }}`}}"
      - name: singleFirst
        value: "{{`{{ workflow.parameters.singleFirst }}`}}"
      - name: xrdProcessConfigUpload
        value: "{{`{{ workflow.parameters.xrdProcessConfigUpload }}`}}"
      - name: calibrationPath
        value: "{{`{{ workflow.parameters.calibrationPath }}`}}"
      - name: maskPath
        value: "{{`{{ workflow.parameters.maskPath }}`}}"
      - name: flatPath
        value: "{{`{{ workflow.parameters.flatPath }}`}}"
    script:
      image: gitlab.diamond.ac.uk:5050/i14/i14_utility/xrd:v0.1
      env:
      - name: HOME
        value: /tmp
      command: [bash]
      source: |
        python -m papermill /tmp/notebook.ipynb /tmp/notebook-parametrized.ipynb \
          -p inpath "{{`{{ workflow.parameters.visitdir }}`}}/scan/i14-{{`{{ inputs.parameters.singleFirst }}`}}.nxs" \
          -p process_configfile "{{`{{ inputs.parameters.xrdProcessConfigUpload }}`}}" \
          -p outpath "{{`{{ inputs.parameters.outputFolder }}`}}/i14-{{`{{ inputs.parameters.singleFirst }}`}}-xrd2d.nxs" \
          -p calibration_path "{{`{{ inputs.parameters.calibrationPath }}`}}" \
          -p mask_path "{{`{{ inputs.parameters.maskPath }}`}}" \
          -p flat_path "{{`{{ inputs.parameters.flatPath }}`}}"
        python -m jupyter nbconvert /tmp/notebook-parametrized.ipynb --to notebook --execute --allow-errors --output xrd2d-notebook --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
        python -m jupyter nbconvert "{{`{{ inputs.parameters.outputFolder }}`}}/xrd2d-notebook.ipynb" --to html --no-input --output xrd2d-output --output-dir "{{`{{ inputs.parameters.outputFolder }}`}}"
      volumeMounts:
      - name: session
        mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      - name: tmp
        mountPath: /tmp
    outputs:
      artifacts:
      - name: xrd2d-notebook
        path: "{{`{{ inputs.parameters.outputFolder }}`}}/xrd2d-notebook.ipynb"
        archive:
          none: {}
      - name: xrd2d-output
        path: "{{`{{ inputs.parameters.outputFolder }}`}}/xrd2d-output.html"
        archive:
          none: {}
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            cpu: 10
            memory: 30Gi
          limits:
            cpu: 10
            memory: 30Gi
    tolerations:
    - key: nodegroup
      operator: Equal
      value: workflows
      effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: nodegroup
              operator: In
              values:
              - workflows
    volumes:
    - name: session
      hostPath:
        path: "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
  - name: xrd2d
    dag:
      tasks:
      - name: files
        template: xrd2d-mount-files
      - name: notebook
        template: xrd2d-notebook
        dependencies: [files]
