apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: extract-raw-projections
  labels:
    workflows.diamond.ac.uk/science-group-extension: "imaging"
  annotations:
    workflows.diamond.ac.uk/repository: "https://github.com/DiamondLightSource/imaging-workflows"
spec:
  entrypoint: extract-raw-projections
  volumeClaimTemplates:
  - metadata:
      name: tmpdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: netapp
  arguments:
    parameters:
    - name: visitdir
      valueFrom:
        configMapKeyRef:
          name: sessionspaces
          key: data_directory
  templates:
  - name: extract-raw-projections
    inputs:
      parameters:
      - name: input
      - name: dataset-path
      - name: projection-indices
      - name: nprocs
        value: 1
      - name: memory
        value: 20Gi
      - name: tmpdir-path
        value: /tmp
      - name: output-filename
        value: projections.tif
    script:
      image: ghcr.io/diamondlightsource/httomo:latest
      command: [/opt/conda/bin/python]
      source: |
        from pathlib import Path

        import h5py
        import tifffile
        import numpy as np


        INPUT_FILEPATH = Path("{{`{{ inputs.parameters.input }}`}}")
        OUT_PATH = "{{`{{ inputs.parameters.tmpdir-path }}`}}/{{`{{ inputs.parameters.output-filename }}`}}"

        string_indices = "{{`{{ inputs.parameters.projection-indices }}`}}".strip(",").replace(" ", "").split(",")
        int_indices = [int(idx) for idx in string_indices]

        with h5py.File(INPUT_FILEPATH, "r") as f:
            dataset = f["{{`{{ inputs.parameters.dataset-path }}`}}"]
            assert isinstance(dataset, h5py.Dataset)
            projections = np.empty(
                (len(int_indices), dataset.shape[1], dataset.shape[2]), dtype=dataset.dtype
            )
            for array_idx, image_idx in enumerate(int_indices):
                projections[array_idx] = dataset[image_idx, :, :]

        tifffile.tifffile.imwrite(OUT_PATH, projections, photometric="minisblack")

      volumeMounts:
      - name: session
        mountPath: "{{`{{ workflow.parameters.visitdir }}`}}"
      - name: tmpdir
        mountPath: "{{`{{ inputs.parameters.tmpdir-path }}`}}"
    volumes:
    - name: session
      hostPath:
        path:  "{{`{{ workflow.parameters.visitdir }}`}}"
        type: Directory
    outputs:
      artifacts:
      - name: projections
        path: "{{`{{ inputs.parameters.tmpdir-path }}`}}/{{`{{ inputs.parameters.output-filename }}`}}"
        archive:
          none: { }
    podSpecPatch: |
      containers:
      - name: main
        resources:
          requests:
            cpu: "{{`{{ inputs.parameters.nprocs }}`}}"
            memory: "{{`{{ inputs.parameters.memory }}`}}"
          limits:
            cpu: "{{`{{ inputs.parameters.nprocs }}`}}"
            memory: "{{`{{ inputs.parameters.memory }}`}}"
    tolerations:
    - key: nodegroup
      operator: Equal
      value: workflows
      effect: NoSchedule
    affinity:
      nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 100
         preference:
           matchExpressions:
           - key: nodegroup
             operator: In
             values:
             - workflows
