apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: artifact-printer
  namespace: mg36964-1
spec:
  entrypoint: ptycho-tomo-run
  templates:
  - container:
      args:
      - '{{ inputs.parameters.command }}'
      command:
      - /bin/sh
      - -c
      image: busybox
      name: ""
      resources: {}
      volumeMounts:
      - mountPath: /tmp
        name: tmpdir
    inputs:
      parameters:
      - name: command
    metadata: {}
    name: bash
    outputs:
      artifacts:
      - name: text
        path: /tmp/some-text.txt
        archive:
          none: { }

      - name: picture1
        path: /tmp/picture1.png
        archive:
          none: { }
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: command
            value: |
              echo "Hello there!" > /tmp/some-text.txt
              wget -O /tmp/picture1.png   https://www.diamond.ac.uk/dam/jcr:cc4ec81e-d480-4821-94c2-a5b982079f94/2024-12-10-Diamond-Aerial-Photo-with-PV.png
        name: create-artifacts
        template: bash
    inputs: {}
    metadata: {}
    name: ptycho-tomo-run
    outputs: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: tmpdir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
