apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: ptycho-tomo-job-artifacts
spec:
  entrypoint: ptycho-tomo-run
  volumeClaimTemplates:
  - metadata:
      name: tmpdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path

  templates:
  - name: bash
    inputs:
      parameters:
      - name: command
      - name: path
    container:
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - "{{ inputs.parameters.command }}"
      volumeMounts:
        - name: tmpdir
          mountPath: /tmp
    outputs:
      artifacts:
      - name: message-artifact
        path: "{{ inputs.parameters.path }}"

  - name: ptycho-tomo-run
    dag:
      tasks:
      - name: create-artifacts
        template: bash
        arguments:
          parameters: 
            - name: command
              value: |
                echo "Hello there!" > /tmp/some-text.txt
                wget -O {{ inputs.parameters.path }}  https://www.diamond.ac.uk/dam/jcr:cc4ec81e-d480-4821-94c2-a5b982079f94/2024-12-10-Diamond-Aerial-Photo-with-PV.png
            - name: path
              value: /tmp/artifact.txt
